server:
  port: 30000

spring:
  application:
    name: memento

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/memento?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Seoul}
    username: ${MYSQL_USER:memento}
    password: ${MYSQL_PASSWORD:memento}
    hikari:
      pool-name: memento-pool
      maximum-pool-size: 12
      minimum-idle: 12
      connection-timeout: 5000
      max-lifetime: 1800000
      idle-timeout: 600000
      validation-timeout: 1000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        jdbc.time_zone: Asia/Seoul
        generate_statistics: false
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 300

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2s
      timeout: 2s

  mail:
    host: ${NAVER_MAIL_HOST}
    port: ${NAVER_MAIL_PORT}
    username: ${NAVER_MAIL_USERNAME}
    password: ${NAVER_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

auth:
  email:
    code-validity-duration: 5m
    resend-cooldown-duration: 5s
    max-attempts: 5
    lockout-duration: 5s
    success-validity-duration: 10m

app:
  jwt:
    issuer: ${spring.application.name}
    at-ttl-seconds: ${JWT_AT_TTL_SECONCDS}
    rt-ttl-seconds: ${JWT_RT_TTL_SECONCDS}
    secret: ${JWT_SECRET_KEY}
    clock-skew-seconds: ${JWT_CLOCK_SKEW_SECONDS}
  oauth2:
    success-redirect: "http://localhost:5173/oauth/callback"   # 프론트 콜백 라우트
    exchange-ttl-seconds: 120                                  # 1회성 교환 코드 TTL

solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  from: ${SOLAPI_FROM}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true