blank_issues_enabled: false
contact_links:
  - name: ğŸš€ ì§ˆë¬¸ / ğŸ¸ ê¸°íƒ€ ë¬¸ì˜
    url: https://github.com/LimdaeIl/memento/discussions
    about: "âœ¨ì¼ë°˜ì ì¸ ì§ˆë¬¸ê³¼ í† ë¡ ì€ Discussionsì— ì‘ì„±í•´ì£¼ì„¸ìš”âœ¨"
